#!/usr/bin/env bash
# Configures a new Ubuntu machine

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
