#!/usr/bin/env bash
# Configures a new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
txt_redirect="\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=JDglMK9sgIQ permanent;\n\t}"
sudo sed -i "/server_name _;/ a \\$txt_redirect" /etc/nginx/sites-available/default
sudo service nginx start
