#!/usr/bin/env bash
# Configures a new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
txt_redirect="\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=JDglMK9sgIQ permanent;\n\t}"
sudo sed -i "/server_name _;/ a \\$txt_redirect" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
txt_error="\n\terror_page 404 /error_404.html; \n\tlocation = /error_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "/server_name _; a \\$txt_error" /etc/nginx/sites-available/default

sudo service nginx start
