#!/usr/bin/env bash
# Configures an Ubuntu server, modifiy the hosts file
# localhost resolves to 127.0.0.2 and
#+ facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/" ~/hosts.new
echo -e "\n8.8.8.8 \tfacebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
